name: PRCop

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - review_requested
      - review_request_removed
  pull_request_review_comment:
    types:
      - created

jobs:
  prcop:
    runs-on: ubuntu-latest
    name: Template Check
    steps:
      - name: Linting Pull Request
        uses: makaroni4/prcop@v1.0.35
        with:
          config-file: '.github/workflows/prcop-config.json'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
